travis:
  secure:
    BINSTAR_TOKEN: OvtlKrbCkwIbJsRi79tGe1ateazJVlZC2QQR5MKEOIB+gR+GuYuTajVzN+/3lXjBtEBeJXghj7NAkZMZgIld9GcuXA9QiiVmyX8/PmVaewxFoy+DjR4Pn2JSlPps4qIvhVN9rXVhUjDKNnt4fS4mGAW+o5jmzBHOOk3vZFlKVDw5JxG/PfN69BAufOF6CVN0HdW93eCNOr5YpBbNOhjGdG7aP6sbVTL2ciy1M15/6lkAjTJ0SedtXdxE+KKPFudxtRG2GjPupmyAKqiHvNuhKxgwdmx/zbA60vNETOQS2+KOjlvyFuQvDmkABd8HWmGRQFLWnmHvlmeiZSi5Bh6EjEw9uCRw33Wo94pYVx3U9/JaG7ZR7A9hDdX9xrhI+cNJDfaZdfSc4bQ5EzDhy7EI/8TBkfHV7qZSBGw2NqLkplut0PIzgDfqzagbZU3M4Mh0Ezxq7dw6dCEsKb/MKjgayYzYzbXR6z/Ktr9DeGSGW410o6Kfqx8/t9XHAdzO9TzDfvzpIMTlTa0wOS6I6RiYQsub7G07M1ez8UszFJOtQM8Zr9aBmst5xzyMvuOJjwNQ2V8sbf/pWsXIUOH8Vv73RnYUDfYQVuJjlf2NfeoVNpHvI+klYMSFxv7PftpKPPRUZx8lrwrUcxbyxHipOLkdpjQIUbuyIdHGge8vPgeJqh8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
